image_name: ros-humble
container_name: ros-humble
ros:
  distro: humble
  type: ros2
option:
  gazebo: true
  volume shared: true
  volume path list:
  - ./ros2_ws
  additionnal:
    dependencies:
      status: true
      content:
        apt:
        - ros-humble-gazebo-ros-pkgs
        - ros-humble-gazebo-ros
        - ignition-fortress
        - ros-humble-ros-ign-interfaces
        - ros-humble-ros-ign-bridge
        - ros-humble-navigation2
        - ros-humble-nav2-bringup
        - nano
        - xterm
        - git
        - tree
        pip:
        - null
    environment:
      status: true
      content: 'ROBOT_ID=9

        LIDAR_TYPE=RSHELIOS

        CAMERA_TYPE=D435

        ROBOT_TYPE=SCOUT_MINI

        START_CAMERA=1

        RVIZ=1'
